import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'
// import type { paths } from './schema/generated' // generated by openapi-typescript
import { CONFIG } from '../model/config'
import type { ApiPaths } from './schema'

export const fetchClient = createFetchClient<ApiPaths>({
  baseUrl: CONFIG.API_BASE_URL
})

export const rqClient = createClient(fetchClient)
